name: AutoDL Available GPUs Check

on:
  schedule:
    - cron: '0 * * * *'
  push:
    branches:
      - main

jobs:
  check_gpus:
    runs-on: ubuntu-latest

    steps:
    - name: Check out repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.11

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run AutoDLAvailableGPUs.py
      run: python AutoDLAvailableGPUs.py